
###############################################################################
# THIS FILE IS GENERATED BY msg_generator/generate.py!!!                      #
# *** DO NOT EDIT DIRECTLY ***                                                #
###############################################################################

'''
Request message types
'''

NO = 100
YES = 101
INTERRUPT = 110
SHUTDOWN = 111
EXEC_CELL = 120
IS_COMPUTING = 130
GET_COMPLETIONS = 140
COMPLETIONS = 141
GET_DOC = 142
DOC = 143
GET_SOURCE = 144
SOURCE = 145


'''
Output message types
'''

STDIN = 0
STDOUT = 1
STDERR = 2
EXCEPT = 10
NEED_STDIN = 90
DONE = 99
