
###############################################################################
# THIS FILE IS GENERATED BY msg_generator/generate.py!!!                      #
# *** DO NOT EDIT DIRECTLY ***                                                #
###############################################################################

'''
Request message types
'''

NO = 100
YES = 101
INTERRUPT = 110
SHUTDOWN = 111
EXEC_CELL = 120


'''
Output message types
'''


