
###############################################################################
# THIS FILE IS GENERATED BY msg_generator/generate.py!!!                      #
# *** DO NOT EDIT DIRECTLY ***                                                #
###############################################################################

from bson import SON, _dict_to_bson

from hdr import Hdr


