
###############################################################################
# THIS FILE IS GENERATED BY msg_generator/generate.py!!!                      #
# *** DO NOT EDIT DIRECTLY ***                                                #
###############################################################################

from bson import SON, _dict_to_bson

from hdr import Hdr

class No(SON):
    """
    No response
    """
    type = 100
    
    def __init__(self):
        SON.__init__(self)
        self.hdr = Hdr(100, 0, 0, 0)
        self.type = 100
        self['t'] = 100
        
        
    def encode(self):
        """
        Returns the encoded representation of this message.
        """
        bodybytes = _dict_to_bson(self, False)
        self.hdr.length = len(bodybytes)
        return self.hdr.encode() + bodybytes
        

class Yes(SON):
    """
    Yes response
    """
    type = 101
    
    def __init__(self):
        SON.__init__(self)
        self.hdr = Hdr(101, 0, 0, 0)
        self.type = 101
        self['t'] = 101
        
        
    def encode(self):
        """
        Returns the encoded representation of this message.
        """
        bodybytes = _dict_to_bson(self, False)
        self.hdr.length = len(bodybytes)
        return self.hdr.encode() + bodybytes
        

class Interrupt(SON):
    """
    Interrupt a computation
    
    Message Arguments:
        timeout -- Time in seconds to wait before responding No (default: 1.0)
    """
    type = 110
    
    def __init__(self, timeout=1.0):
        SON.__init__(self)
        self.hdr = Hdr(110, 0, 0, 0)
        self.type = 110
        self['t'] = 110
        self['timeout'] = timeout
        
    def encode(self):
        """
        Returns the encoded representation of this message.
        """
        bodybytes = _dict_to_bson(self, False)
        self.hdr.length = len(bodybytes)
        return self.hdr.encode() + bodybytes
        

class Shutdown(SON):
    """
    Shutdown Message
    """
    type = 111
    
    def __init__(self):
        SON.__init__(self)
        self.hdr = Hdr(111, 0, 0, 0)
        self.type = 111
        self['t'] = 111
        
        
    def encode(self):
        """
        Returns the encoded representation of this message.
        """
        bodybytes = _dict_to_bson(self, False)
        self.hdr.length = len(bodybytes)
        return self.hdr.encode() + bodybytes
        

class ExecCell(SON):
    """
    ExecCell Message
    
    Message Arguments:
        source -- Source code of the cell to execute
    """
    type = 120
    
    def __init__(self, source):
        SON.__init__(self)
        self.hdr = Hdr(120, 0, 0, 0)
        self.type = 120
        self['t'] = 120
        self['source'] = source
        
    def encode(self):
        """
        Returns the encoded representation of this message.
        """
        bodybytes = _dict_to_bson(self, False)
        self.hdr.length = len(bodybytes)
        return self.hdr.encode() + bodybytes
        

class IsComputing(SON):
    """
    Returns Yes or No
    """
    type = 130
    
    def __init__(self):
        SON.__init__(self)
        self.hdr = Hdr(130, 0, 0, 0)
        self.type = 130
        self['t'] = 130
        
        
    def encode(self):
        """
        Returns the encoded representation of this message.
        """
        bodybytes = _dict_to_bson(self, False)
        self.hdr.length = len(bodybytes)
        return self.hdr.encode() + bodybytes
        
